package:
  name: ncbi-datasets-cli
  version: 12.10.2

requirements:
  build:
    - bazel<4.0.0
    - go>=1.16.4

source:
  path: ../

test:
  commands:
    - datasets version
    - dataformat version
